name: Build and publish container image to GitHub Container Registry

on: push

jobs:
  ghcr:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/game-update-notifier:${{ steps.vars.outputs.tag }}
